Improvements to preliminary cortex m3/4/7 port.
- Removed superfluous code that was brought in out of desparation yesterday
- Cleaning up stuff, now that I know the fundamental code works
- Fixing linker args correctly so that "undefined reference to 'x'" doesn't occur