Merged revision(s) 298-336 from trunk/embedded: Implementing a priority-map module, eliminating the scheduler's limit of 8 priority levels which was previously imposed on the system. The new maximum number of thread priorities is limited only to the available RAM of the host system.
........
Updating reference to priority map in the docs.
Correcting the logic used to generate priomaps, such that the correct types are used for the right range of priorites.


........
Updating copyrights to 2016

........
Fixing priority mapping for 2-level bitmap case.


........
Fixing scheduler to use correct defines from mark3cfg.h instead of scheduler.h for determining number of thread priorities.


........
Adding preliminary circular-buffer based stream class


........
Adding support for assembly-language objects.


........
Adding very-rough prototype cortex M3/4/7 support to the kernel
........
Adding rough kernel setup example for cortex m3


........
Improvements to preliminary cortex m3/4/7 port.

- Removed superfluous code that was brought in out of desparation yesterday
- Cleaning up stuff, now that I know the fundamental code works
- Fixing linker args correctly so that "undefined reference to 'x'" doesn't occur


........
-Ensure that the official test suite is only built for AVR, and not for other architectures where support for kernel-aware debugging, and built-in drivers may not exist.



........
- Cleaning up cortex m0 + m3 ports.  
- Optimize context switching for m3 and up, which has a more capable ldmia/stmia.


........
- Adding preliminary cortex m4-f support
- Fixing usage of isb in cortex ports for control register modification
- Fixing demo stack-size usage in thread init.


........
Cleaning up tabs.  Making sure that cortex m3/m4 files are not misrepresented as cortex m0 in the headers.  Documentation for those ports needs more work, however.

........
-Fixing kernel bug.  Corner-case where multiple threads are initialized at the same highest priority level before the kernel is started.  The first thread that runs won't relinquish control until it voluntarily blocks.  The fix ensures that round-robin scheduling is properly applied in this case.
-Adding set_target.sh script, allowing for developers to quickly reconfigure the build environment and switch from one target to another quickly.


........
Reverting de-optimization in cm4f build.
x

........
Adding support for atmega2560


........
-Resetting default config to use tickless timers
-Fixing timing prescaler on 2560


........
Fixing up timer defines for ports.  Errors will be generated on build if attempting to build tickless timers on an unsupported part.


........
Adding errors regarding the user of KERNEL_USE_IDLE_FUNC on platforms where it is not supported.


........
Fixing up build, export, and profiling scripts for new features and targets.


........
Adding missing atmega2560 builds


........
- Renaming cm0/stm32f0 port to cm0/generic (modifying related scripts as well)
- All cortex-m targets to build without external library depenencies, based on ARM's BSD-licensed CMSIS headers
- Cleaned up cortex-m platform.mak files, removing references to external paths


........
-Updating manual and readme to reflect new configuration scripts
-Updating lab code to use correct stack sizes as part of thread init.

........
Fixing unit tests for tick-based timer compatibility.


........
-Adding compile-time error macro to demos that only build with KERNEL_USE_IDLE_FUNC
-Prevent ARM targets from building with KERNEL_USE_IDLE_FUNC by default, but set as default for AVR and MSP430


........
- Adding placement-new operator for all kernel object types, allowing for them to be dynamically allocated from user-created heaps, without overriding global new/free
- Added helper methods to AutoAlloc class for allocating/initializing kernel objects (wrapper functions for placement-new) 


........
Adding missing "stddef.h" define for arduino port, necessary for autoalloc support.


........
Beginnings of Mark3C library -- Mark3 with C-language bindings.  Preliminary work supports AVR only, needs further development for MSP/ARM support.


........
Add code in mark3c to automagically generate the size of kernel objects when declared in C.  This should allow mark3c to run on all supported targets.


........
Refactoring kernel headers to support the mark3c, C-language binding lib. 


........
Adding documentation to the cm3 example code describing how to build code with vendor libs and linker scripts


........
- Adding examples for mark3c APIs
- Adding Arena unit test
........
-Fixed mark3c example code
-Fixed mark3c library -- object init calls now rely on placement-new to guarantee proper object behavior.
........
-Adding documentation on mark3c API
-Define a boilerplace __cxa_pure_virtual() in mark3c
-Fixe lab2 for mark3c
-Fix set_target.sh to print usage (and not exit the current terminal) when called with incorrect parameters


........
- Adding remaining mark3c "lab" examples for parity with mark3 


........
- Working on docs + release notes
- Adding C-based driver implementation for mark3c library


........
More Documentation 


........
Moar docs


........